# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  azureSubscriptionId: 'a6f564d4-e424-4cbb-b881-79aef78c437e'
  
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'SecuredContainerRegistry'
  imageRepository: 'securedazurelib'
  containerRegistry: 'securedcontainerregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/SecuredResources/SecuredWebApi/Dockerfile'
  tag: '$(Build.BuildId)'


stages:
- stage: ARM_Deployment
  displayName: 'ARM Deployment'
  jobs:
  - job: DeployArmTemplates
    displayName: "Deploy Arm Templates"
    pool:
      vmImage: ubuntu-latest
    steps:      
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'ARM deployment: Network'
      enabled: false
      inputs:
        azureResourceManagerConnection: 'network-sp'
        subscriptionId: $(azureSubscriptionId)
        resourceGroupName: 'Network-rg'
        location: 'West Europe'
        csmFile: 'Arm-Templates/network.json'
        csmParametersFile: 'Arm-Templates/network.parameters.json'
        deploymentName: 'arm-cd-release'
            
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'ARM deployment: Resources'
      enabled: false
      inputs:
        azureResourceManagerConnection: 'Managed-rg-sp'
        subscriptionId: $(azureSubscriptionId)
        resourceGroupName: 'Managed-rg'
        location: 'West Europe'
        csmFile: 'Arm-Templates/resources.json'
        csmParametersFile: 'Arm-Templates/resource.parameters.json'
        deploymentName: 'arm-cd-release'

- stage: DockerBuild
  displayName: 'Build and register docker image'
  dependsOn: ARM_Deployment
  condition: succeeded()
  jobs:
  - job: DockerBuild
    displayName: "Build docker image and deploy"
    pool: 
        vmImage: ubuntu-latest

    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildNumber)
- stage: LegacyStage
  displayName: 'Quality Check'
  dependsOn: ARM_Deployment
  condition: succeeded()
  jobs:
  - job: BuildSource
    displayName: "Build source code"
    pool:
      vmImage: windows-latest
    steps:
      - task: NuGetToolInstaller@1
      - task: NuGetCommand@2
        enabled: false
        inputs:
          restoreSolution: '$(solution)'

      - task: SonarCloudPrepare@12
        enabled: false
        inputs:
          SonarCloud: 'SonarCloud'
          organization: 'pouya-panahy'
          scannerMode: 'MSBuild'
          projectKey: 'PouyaPanahy_secured-azure-lib'
          projectName: 'PouyaPanahy_secured-azure-lib'
          
      - task: VSBuild@12
        enabled: false
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - task: SonarCloudAnalyze@12
        enabled: false

      - task: SonarCloudPublish@12
        enabled: false
        inputs:
          pollingTimeoutSec: '300'
