# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
- stage: Deploy_Resources
  jobs:
  - job: DeployArmTemplates
    displayName: "Deploy Arm Templates"
    steps:
    - script: 'tzutil /s "W. Europe Standard Time"'
      displayName: 'Set Timezone to W. Europe'
      
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'ARM Template deployment: Resources'
      inputs:
        azureResourceManagerConnection: 'Managed-rg-sp'
        subscriptionId: 'a6f564d4-e424-4cbb-b881-79aef78c437e'
        resourceGroupName: 'Managed-rg'
        location: 'West Europe'
        csmFile: 'Arm-Templates/resources.json'
        csmParametersFile: 'Arm-Templates/resources.parameters.json'
        deploymentName: 'arm-cd-release'
    