# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
- stage: Deploy_Resources
  jobs:
  - job: DeployArmTemplates
    displayName: "Deploy Arm Templates"
    steps:      
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'ARM deployment: Network'
      inputs:
        azureResourceManagerConnection: 'network-sp'
        subscriptionId: 'a6f564d4-e424-4cbb-b881-79aef78c437e'
        resourceGroupName: 'Network-rg'
        location: 'West Europe'
        csmFile: 'Arm-Templates/network.json'
        csmParametersFile: 'Arm-Templates/network.parameters.json'
        deploymentName: 'arm-cd-release'
            
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'ARM deployment: Resources'
      inputs:
        azureResourceManagerConnection: 'Managed-rg-sp'
        subscriptionId: 'a6f564d4-e424-4cbb-b881-79aef78c437e'
        resourceGroupName: 'Managed-rg'
        location: 'West Europe'
        csmFile: 'Arm-Templates/resources.json'
        csmParametersFile: 'Arm-Templates/resource.parameters.json'
        deploymentName: 'arm-cd-release'
    
    - task: WhiteSource@21