# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Deploy_Resources
  jobs:
  - job: DeployArmTemplates
    displayName: "Deploy Arm Templates"
    pool:
      vmImage: ubuntu-latest
    steps:      
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'ARM deployment: Network'
      inputs:
        azureResourceManagerConnection: 'network-sp'
        subscriptionId: 'a6f564d4-e424-4cbb-b881-79aef78c437e'
        resourceGroupName: 'Network-rg'
        location: 'West Europe'
        csmFile: 'Arm-Templates/network.json'
        csmParametersFile: 'Arm-Templates/network.parameters.json'
        deploymentName: 'arm-cd-release'
            
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'ARM deployment: Resources'
      inputs:
        azureResourceManagerConnection: 'Managed-rg-sp'
        subscriptionId: 'a6f564d4-e424-4cbb-b881-79aef78c437e'
        resourceGroupName: 'Managed-rg'
        location: 'West Europe'
        csmFile: 'Arm-Templates/resources.json'
        csmParametersFile: 'Arm-Templates/resource.parameters.json'
        deploymentName: 'arm-cd-release'
    
  - job: BuildSource
    displayName: "Build source code"
    pool:
      vmImage: windows-latest
    steps:
      - task: NuGetToolInstaller@1
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'

      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'SonarCloud'
          organization: 'pouya-panahy'
          scannerMode: 'MSBuild'
          projectKey: 'secured-azure-lib'
          projectName: 'secured-azure-lib'
          
      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - task: SonarCloudAnalyze@1

      - task: SonarCloudPublish@1
        inputs:
          pollingTimeoutSec: '300'